[tool.poetry]
name = "pyfk"
version = "0.4.0"
description = "Pyfk is the python version of FK used to calculate the Green's function and the synthetic waveforms for the 1D Earth model."
authors = ["Ziyi Xi <xiziyi2015@gmail.com>"]
license = "Apache-2.0"
readme = "README.rst"
homepage = "https://github.com/ziyixi/pyfk"
classifiers = [
        "Development Status :: 5 - Production/Stable",
        "Environment :: Console",
        "Environment :: GPU",
        "Intended Audience :: Science/Research",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: Apache Software License",
        "Operating System :: OS Independent",
        "Programming Language :: Python",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Topic :: Scientific/Engineering",
        "Topic :: Scientific/Engineering :: Physics",
    ]

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
numpy = ">=1.23.0"
obspy = ">=1.4.0"
Cython = ">=3.0.0"
scipy = ">=1.10.0"
cysignals = ">=1.11.2"
mpi4py = { version = ">=3.1.3", optional = true }

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
coverage = ">=7.0"
pytest = ">=7.4.0"
pytest-mpi = ">=0.6"
autopep8 = ">=2.0.0"
hypothesis = ">=6.0.0"
ruff = ">=0.1.0"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
Sphinx = ">=7.0"
pydata-sphinx-theme = ">=0.14"
sphinx-autoapi = ">=3.0"
jupyter-sphinx = ">=0.5"
sphinx-copybutton = ">=0.5.0"

[tool.poetry.extras]
mpi = ["mpi4py"]

[build-system]
requires = [
    "poetry-core>=1.0.0",
    "setuptools",
    "numpy",
    "obspy",
    "cython>=3.0",
    "scipy",
    "cysignals",
    "mpi4py"
]
build-backend = "poetry.core.masonry.api"

[tool.poetry.build]
# The allows us to build C extensions (using Cython). Unstable feature
# https://github.com/python-poetry/poetry/issues/2740#issuecomment-666551481
script = "setup_cython.py"
# see https://github.com/python-poetry/poetry/issues/2740#issuecomment-860744196
generate-setup-file = true