name: Publish Python 🐍 distributions 📦 to PyPI
on:
  release:
    types: [published]
jobs:
  # Run all tests including MPI tests before publishing
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install OpenMPI
        run: |
          sudo apt update
          sudo apt install openmpi-bin libopenmpi-dev -y

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run standard tests
        run: |
          pip install .
          pip install pytest pytest-mpi
          pytest --pyargs pyfk

      - name: Run MPI tests
        run: |
          pip uninstall pyfk -y
          pip install mpi4py
          PYFK_USE_MPI=1 pip install ".[mpi]"
          export OMPI_ALLOW_RUN_AS_ROOT=1
          export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
          mpirun --oversubscribe -np 1 pytest --with-mpi --pyargs pyfk
          mpirun --oversubscribe -np 3 pytest --with-mpi --pyargs pyfk

  pypi:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: "1.8.5"
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root
      - name: build and publish
        run: |
          poetry build -f sdist
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish